import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/components/QueryProvider";
import { Poppins } from "next/font/google"

const poppins = Poppins({
  variable: "--font-poppins",
  weight: "100",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Savely",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
