import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/components/QueryProvider";
import { Poppins } from "next/font/google";
import AuthProvider from "@/components/AuthProvider";
import { createClient } from "@/utils/supabase/server"; // <-- use your existing server helper

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "400", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Savely",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // SSR: detect logged-in user
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  let username: string | null = null;
  let points: number | null = null;
  if (user) {
    const { data } = await supabase
      .from("profiles")
      .select("username, points")
      .eq("id", user.id)
      .single();
    username = data?.username ?? null;
    points = data?.points ?? null;
  }

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`} suppressHydrationWarning>
        <QueryProvider>
          <AuthProvider initialUser={user} initialUsername={username}>
            {children}
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
